FROM webbben/pygeoapi-river-runner:stable
#last update 2021-10-8T16:40:00-5

#add requirements and mods
COPY ./pygeoapi.config.gcp.yml /pygeoapi/local.config.yml
COPY ./schemas.opengis.net /opt/schemas.opengis.net
COPY ./pygeoapi-skin-dashboard /skin-dashboard
