FROM webbben/pygeoapi-river-runner:latest
#last update 2021-10-05T16:26

#add requirements and mods
COPY ./pygeoapi.config.gcp.yml /pygeoapi/local.config.yml
COPY ./schemas.opengis.net /opt/schemas.opengis.net
COPY ./pygeoapi-skin-dashboard /skin-dashboard
