FROM webbben/pygeoapi-river-runner:latest

ADD https://svn.osgeo.org/gdal/trunk/gdal/swig/python/samples/ogr2ogr.py /pygeoapi/ogr2ogr.py

COPY ./entrypoint.sh /entrypoint.sh
RUN ["chmod", "+x", "/entrypoint.sh"]

WORKDIR /pygeoapi
ENTRYPOINT ["/entrypoint.sh"]
